export type QuestionOption = {
  key: "A" | "B" | "C" | "D";
  text: string;
};

export type LevelQuestion = {
  n: number; // 1, 2, 3, 4
  code: string;
  exhibitTitle: string;
  clue: string;
  question: string;
  options: QuestionOption[];
  correctAnswer: "A" | "B" | "C" | "D";
  revealedLetter: string; // The letter unlocked if answered correctly (e.g. 'C', 'O', 'N', 'T')
  explanation: string;
};

export const SECRET_WORD = "CONTAGION";
export const SECRET_WORD_LENGTH = 9;

export const QUESTIONS: LevelQuestion[] = [
  {
    n: 1,
    code: "EXHIBIT-01",
    exhibitTitle: "Exhibit 01 · Washington Testimony",
    clue: "The minister from Washington delivered a famous statement during the opening courtroom proceedings.",
    question: "What were the five words mentioned by the minister from Washington?",
    options: [
      { key: "A", text: "We cannot pay you back" },
      { key: "B", text: "We want to borrow more" },
      { key: "C", text: "We want to lend more" },
      { key: "D", text: "We do not need money" },
    ],
    correctAnswer: "A",
    revealedLetter: "C",
    explanation: "Correct! The Washington minister stated: 'We cannot pay you back', signaling sovereign default risk.",
  },
  {
    n: 2,
    code: "EXHIBIT-02",
    exhibitTitle: "Exhibit 02 · Oil Export Liquidity",
    clue: "Massive export earnings from global oil shocks flooded Western commercial banks with foreign exchange.",
    question: "What is the term given for the money obtained from oil exporting?",
    options: [
      { key: "A", text: "Oildollars" },
      { key: "B", text: "Petrodollars" },
      { key: "C", text: "Oileuros" },
      { key: "D", text: "Pertroeuros" },
    ],
    correctAnswer: "B",
    revealedLetter: "O",
    explanation: "Correct! 'Petrodollars' refers to revenues generated by petroleum exports, recycled as foreign loans.",
  },
  {
    n: 3,
    code: "EXHIBIT-03",
    exhibitTitle: "Exhibit 03 · US Monetary Tightening",
    clue: "Federal Reserve Chair Paul Volcker dramatically increased interest rates to halt runaway US inflation.",
    question: "What was the inflation rate of US in 1979?",
    options: [
      { key: "A", text: "14%" },
      { key: "B", text: "16%" },
      { key: "C", text: "18%" },
      { key: "D", text: "20%" },
    ],
    correctAnswer: "A",
    revealedLetter: "N",
    explanation: "Correct! US inflation peaked near 14% in 1979, triggering aggressive Fed interest rate hikes.",
  },
  {
    n: 4,
    code: "EXHIBIT-04",
    exhibitTitle: "Exhibit 04 · International Rescue Initiatives",
    clue: "Three major restructuring mechanisms were deployed to resolve Latin America's sovereign debt crisis.",
    question: "What were the three rescue attempts taken by US?",
    options: [
      { key: "A", text: "Bakery plan, Brandy plan, IMF programs" },
      { key: "B", text: "Mega plan, Economic plan, and IMF meetings" },
      { key: "C", text: "Escape plan, Breakout plan, and RDA programs" },
      { key: "D", text: "Baker plan, Brady plan, and IMF programs" },
    ],
    correctAnswer: "D",
    revealedLetter: "T",
    explanation: "Correct! The Baker Plan, Brady Plan, and IMF structural programs were the key rescue initiatives.",
  },
];

export const getQuestion = (n: number) => QUESTIONS.find((q) => q.n === n);